Add DTA position in Staff page
zabartcc/ui pull request #10
Opened 2022-11-07 16:39 UTC by Frafire

2022-11-08 16:23 UTC, cdconn00 commented
Changed the base branch to development. Let's start merging feature branch -> development -> release branch -> master

2022-11-09 15:38 UTC, Frafire commented
@cdconn00  request review, the work is finish

2022-11-09 15:46 UTC, cdconn00 commented
@Frafire commit messages should describe what the commit does, not just say the file that was changed.

Good examples:
- "Add new component for team members."
- "Delete needed code."
- "Modify hook to be more performant."

Bad examples:
- "Update view.js"
- "Add hook.js"

2022-11-09 15:53 UTC, cdconn00 commented
![image](https://user-images.githubusercontent.com/30357632/200877426-85a1d1f0-9d44-4343-a1ca-4c16cea23b30.png)

DTA should not appear in `ARTCC Staff`.

2022-11-09 15:53 UTC, JWZABARTCC commented
Approved, thanks Gio

2022-11-09 15:54 UTC, JWZABARTCC approved these changes

2022-11-09 15:59 UTC, cdconn00 commented
![image](https://user-images.githubusercontent.com/30357632/200878981-cd7d53b4-85b3-4218-8d3d-7694d51d6bb1.png)


There should be a line connecting ta and dta

2022-11-09 16:05 UTC, cdconn00 requested changes
See changes requested.

2022-11-09 16:05 UTC, cdconn00 commented on src/views/controllers/Staff.vue
> +.border_long2{
add linebreak between classes.

2022-11-09 16:05 UTC, cdconn00 commented on src/views/controllers/Staff.vue
> +.border_middle {
add linebreak between classes.

2022-11-09 16:47 UTC, Frafire commented on src/views/controllers/Staff.vue
> +		<!-- END STAFF ROW -->
line 10, div is changed to ROW

2022-11-09 16:48 UTC, Frafire commented on src/views/controllers/Staff.vue
> +						<!-- the middle line  -->
i  add 	<!-- the middle line between position DTA TA  -->

2022-11-09 16:48 UTC, Frafire commented on src/views/controllers/Staff.vue
> +						<!-- the middle line  -->
the middle line between position DTA TA

2022-11-09 16:51 UTC, Frafire commented on src/views/controllers/Staff.vue
> +.card1{
cardi 1 rename card-distance-trainigstaff

2022-11-09 16:52 UTC, Frafire commented on src/views/controllers/Staff.vue
> +.border_long2{
is a second type of border long, the difference is in the settings

2022-11-09 17:04 UTC, Frafire commented on src/views/controllers/Staff.vue
> +// is use for distance between TA and DTA card
resolve

2022-11-09 17:30 UTC, cdconn00 commented on src/views/controllers/Staff.vue
> +.border_long2{
won't hold the review up on this, but not a big fan of putting a number instead of something more meaningful

2022-11-09 17:32 UTC, cdconn00 requested changes

2022-11-09 17:32 UTC, cdconn00 commented on src/views/controllers/Staff.vue
> +		<!-- END STAFF ROW -->
Can this comment be moved to before line 66? This comment is several div's outside of the first comment.

2022-11-09 20:55 UTC, cdconn00 approved these changes

2022-11-09 21:35 UTC, merged