[ZAB-13] Traning Submitting
zabartcc/ui pull request #32
Opened 2022-12-15 15:11 UTC by Frafire

## [ZAB-13]

---

### Summary

- Send Traning form to VATUSA

---

### Testing

1. Run all tests.

---

### Post-Deployment Validation

- Add validation steps here...

---

[ZAB-13]: https://zabartcc.atlassian.net/browse/ZAB-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-12-19 14:34 UTC, cdconn00 commented
Fixed your PR comment, please look at the styling and try to make your PR style like that. It is easier to read that way. 

Reviewing this today.

2022-12-19 14:38 UTC, cdconn00 requested changes
See requested changes.

2022-12-19 14:38 UTC, cdconn00 commented on src/views/instructor/training/EditSession.vue
> +
I don't understand this comment.

2022-12-19 14:38 UTC, cdconn00 commented on src/views/instructor/training/EditSession.vue
>  		},
Add a blank line like you did on line 157, or delete this one.

2022-12-19 14:38 UTC, cdconn00 commented on src/views/instructor/training/EditSession.vue
> +				await vatusaApiAuth.post(`/user/${this.session.cid}/training/record`, formData);
Add new line before this.

2022-12-19 14:38 UTC, cdconn00 commented on src/views/instructor/training/EditSession.vue
> +				this.toastSuccess('Traning Record issued');
Should be ''Training Session Submitted". Or "Training Notes Submitted"

Any preference here @JWZABARTCC ?

2022-12-19 15:37 UTC, Frafire commented
> @Frafire what branch did you create `GF-submit-traning` off of?

Master

2022-12-19 15:39 UTC, Frafire commented on src/views/instructor/training/EditSession.vue
> +
my fault i forgot to change that

2022-12-19 15:42 UTC, Frafire commented on src/views/instructor/training/EditSession.vue
> +				await vatusaApiAuth.post(`/user/${this.session.cid}/training/record`, formData);
before await?

2022-12-19 16:24 UTC, cdconn00 commented
> > @Frafire what branch did you create `GF-submit-traning` off of?
> 
> Master

Okay, that's making this PR a little messy. When we do a new feature we want to merge off development and then merge back into development.

Master shouldn't need to be branched off of, except in rare cases for hotfixes.

Can you make a new branch of development, and add your changes there? Then open a new PR.

2022-12-20 08:18 UTC, Frafire commented
> > > @Frafire what branch did you create `GF-submit-traning` off of?
> 
> > 
> 
> > Master
> 
> 
> 
> Okay, that's making this PR a little messy. When we do a new feature we want to merge off development and then merge back into development.
> 
> 
> 
> Master shouldn't need to be branched off of, except in rare cases for hotfixes.
> 
> 
> 
> Can you make a new branch of development, and add your changes there? Then open a new PR.

got it, this afternoon i create new PR thanks you Cole

2022-12-20 14:23 UTC, closed without merging